name: Mirror to Codeberg

permissions:
    contents: read

on:
    push:
        branches:
            - master

jobs:
    mirror:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Push to Codeberg
              run: |
                  git remote add codeberg https://enty:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/enty/meowping.git
                  git push --mirror codeberg
